export const weeks = [
  {
    id: 1,
    title: 'Semana 1',
    subtitle: 'Reactivación',
    note: null,
    days: [
      {
        id: 'day-00',
        date: 'Lunes 9',
        type: 'run',
        emoji: '🏃',
        title: 'Trote — 6 km',
        detail: 'Primer entrenamiento del plan. 6 km completados a 5:47/km — buen ritmo de base para arrancar.',
      },
      {
        id: 'day-01',
        date: 'Martes 10',
        type: 'strength',
        emoji: '💪',
        title: 'Fuerza — Tren inferior + core',
        detail: [
          {
            title: 'Calentamiento (5 min)',
            items: [
              'Círculos de cadera: 10 hacia cada lado parado',
              'Sentadillas lentas sin peso: 10 reps, bajando en 3 seg',
              'Elevación de rodillas al pecho caminando: 10 pasos',
              'Círculos de tobillo sentado: 10 c/lado',
            ],
          },
          {
            title: 'Circuito principal — hacé 3 rondas, 60 seg descanso entre rondas',
            items: [
              'Sentadillas clásicas ×15 — pies a ancho de hombros, bajás hasta paralelo, espalda recta',
              'Zancadas alternas ×12 c/pierna — paso largo, rodilla trasera casi toca el piso',
              'Puente de glúteos ×15 — acostado boca arriba, pies apoyados, subís las caderas y apretás glúteos 2 seg arriba',
              'Sentadilla sumo ×15 — pies bien abiertos y puntas hacia afuera, bajás más profundo',
              'Plancha frontal ×40 seg — codos en el piso, cuerpo recto, no hundas la cadera',
              'Plancha lateral ×30 seg c/lado — cadera arriba, cuerpo en línea recta',
            ],
          },
          {
            title: 'Finisher core (sin descanso entre ejercicios)',
            items: [
              'Abdominales bicicleta ×20 — codo al talón opuesto, lento y controlado',
              'Superman ×15 — boca abajo, levantás brazos y piernas juntos, sostenés 2 seg',
              'Dead bug ×10 c/lado — acostado, espalda pegada al piso, bajás brazo y pierna opuesta sin despegar la zona lumbar',
            ],
          },
          {
            title: 'Estiramiento final (8 min)',
            items: [
              'Cuádriceps: parado, tobillo al glúteo, 35 seg c/lado',
              'Isquiotibiales: sentado, piernas extendidas, inclinación al frente, 35 seg',
              'Psoas/cadera: estocada baja con rodilla en el piso, 40 seg c/lado',
              'Glúteos: acostado, rodilla al pecho cruzada (figura 4), 30 seg c/lado',
              'Espalda baja: "pose del niño" en el piso, brazos extendidos, 1 min',
            ],
          },
        ],
      },
      {
        id: 'day-02',
        date: 'Miércoles 11',
        type: 'strength',
        emoji: '💪',
        title: 'Fuerza — Tren superior + core',
        detail: [
          {
            title: 'Calentamiento (5 min)',
            items: [
              'Círculos de hombros hacia adelante y atrás: 15 c/dirección',
              'Rotación torácica sentado: 10 c/lado (sentado en el piso con piernas cruzadas)',
              'Puente de hombros: acostado, rolar la columna lentamente ×10',
              'Apertura de pecho: manos entrelazadas atrás, pecho hacia arriba, 5 respiraciones',
            ],
          },
          {
            title: 'Circuito principal — hacé 3 rondas, 60 seg descanso entre rondas',
            items: [
              'Flexiones clásicas ×máximo (mínimo 5) — si es muy difícil, hacelas con rodillas en el piso hasta que salgan bien',
              'Flexiones con manos juntas (tríceps) ×10 — manos cerca, codos pegados al cuerpo al bajar',
              'Flexiones en pique ×10 — cadera arriba como una "A", cabeza entre los brazos, cargás los hombros',
              'Fondos en silla ×12 — sentado al borde de una silla, brazos extendidos, bajás doblando los codos',
              'Plancha con toque de hombro ×10 c/lado — en posición de flexión, tocás el hombro opuesto sin rotar la cadera',
              'Superman con apertura de brazos ×12 — boca abajo, brazos en "Y", levantás y bajás lento',
            ],
          },
          {
            title: 'Finisher core',
            items: [
              'Plancha frontal ×45 seg',
              'Russian twist ×20 (10 c/lado) — sentado, piernas levantadas, rotás el tronco tocando el piso a cada lado',
              'Bird-dog ×12 c/lado — en cuatro apoyos, extendés brazo y pierna opuestos, sostenés 2 seg',
              'Crunch clásico ×15 — manos detrás de la cabeza, subís solo el tronco superior, no jalés el cuello',
            ],
          },
          {
            title: 'Estiramiento final (8 min)',
            items: [
              'Pecho: manos entrelazadas atrás, empujás el pecho hacia adelante, 40 seg',
              'Tríceps: brazo doblado sobre la cabeza, la otra mano empuja el codo, 30 seg c/lado',
              'Hombros: brazo cruzado al pecho, 30 seg c/lado',
              'Gemelos: contra la pared, pierna trasera extendida, 35 seg c/lado (ya que mañana corrés)',
              'Isquiotibiales: sentado en el piso, 35 seg',
              'Espalda baja: pose del niño, 1 min',
            ],
          },
        ],
      },
      {
        id: 'day-03',
        date: 'Jueves 12',
        type: 'run',
        emoji: '🏃',
        title: 'Trote — 8 km',
        detail: 'Ritmo moderado 5:50–6:10/km. Podés intercalar: 5 min a ritmo medio + 2 min suave. Terminá sintiéndote que podías seguir.',
      },
      {
        id: 'day-04',
        date: 'Viernes 13',
        type: 'free',
        emoji: '🎉',
        title: 'Día libre',
        detail: 'Disfrutá. Solo intentá no trasnochar demasiado — tenés una rodada el domingo.',
      },
      {
        id: 'day-05',
        date: 'Sábado 14',
        type: 'free',
        emoji: '🎉',
        title: 'Día libre',
        detail: 'Descansá. Hidratate bien. Mañana es la rodada larga de la semana.',
      },
      {
        id: 'day-06',
        date: 'Domingo 15',
        type: 'run',
        emoji: '🏃',
        title: 'Rodada larga — 13–14 km ⭐',
        detail: 'Ritmo suave 6:10–6:30/km. Sin apuro. Si llegás a 12 km y estás bien, seguí. Llevá agua o planificá por dónde recargar. Este entrenamiento es la base de todo.',
      },
    ],
  },
  {
    id: 2,
    title: 'Semana 2',
    subtitle: 'Consolidación',
    note: null,
    days: [
      {
        id: 'day-07',
        date: 'Lunes 16',
        type: 'rest',
        emoji: '😴',
        title: 'Descanso o caminata',
        detail: 'Recuperación activa post-rodada larga. Las piernas necesitan asimilar el trabajo del domingo.',
      },
      {
        id: 'day-08',
        date: 'Martes 17',
        type: 'run',
        emoji: '🏃',
        title: 'Trote suave — 6 km',
        detail: 'Piernas livianas, ritmo 6:10–6:20/km. Solo activación, sin exigirse.',
      },
      {
        id: 'day-09',
        date: 'Miércoles 18',
        type: 'strength',
        emoji: '💪',
        title: 'Fuerza — Tren inferior potencia',
        detail: [
          {
            title: 'Calentamiento (5 min)',
            items: [
              'Trote en el lugar: 2 min levantando bien las rodillas',
              'Sentadillas lentas de movilidad ×10',
              'Balanceos de pierna adelante-atrás: 10 c/lado',
              'Balanceos de pierna lateral: 10 c/lado',
            ],
          },
          {
            title: 'Circuito principal — 3 rondas, 90 seg descanso (más intenso que semana 1)',
            items: [
              'Sentadilla con salto ×10 — bajás normal, salto explosivo arriba, aterrizás suave doblando las rodillas',
              'Sentadilla búlgara ×10 c/pierna — pie trasero apoyado en una silla, bajás hasta que la rodilla trasera casi toca el piso. El más difícil — tomátelo tranquilo',
              'Step-up en silla ×12 c/pierna — subís y bajás controlado, el glúteo de la pierna que trabaja hace todo',
              'Peso muerto a una pierna ×10 c/lado — parado en una pierna, inclinás el tronco hacia adelante mientras la pierna libre va atrás, espalda recta',
              'Puente de glúteos con pausa ×15 — arriba, apretás glúteos y sostenés 3 seg antes de bajar',
              'Sentadilla isométrica en la pared ×45 seg — espalda contra la pared, rodillas a 90°, sostenés',
            ],
          },
          {
            title: 'Finisher core + estabilidad',
            items: [
              'Mountain climbers ×20 — en posición de flexión, alternás rodillas al pecho rápido',
              'Plancha con extensión de cadera ×10 c/pierna — en plancha de codos, levantás una pierna recta, sostenés 2 seg',
              'Plancha lateral con elevación de cadera ×12 — en plancha lateral, bajás y subís la cadera',
              'Abdominales bicicleta ×25 — más rápido que la semana pasada',
            ],
          },
          {
            title: 'Estiramiento final (10 min — más largo porque mañana corrés)',
            items: [
              'Gemelos contra la pared: 40 seg c/lado, dos veces',
              'Isquiotibiales sentado al frente: 40 seg, dos veces',
              'Cuádriceps: tobillo al glúteo, 35 seg c/lado',
              'Psoas: estocada baja con cadera hacia adelante, 45 seg c/lado',
              'Glúteos: figura 4 acostado, 35 seg c/lado',
              'TFL/cintilla: parado, cruzás una pierna adelante de la otra, inclinás el tronco al lado contrario, 30 seg c/lado',
              'Espalda baja: pose del niño, 1.5 min',
            ],
          },
        ],
      },
      {
        id: 'day-10',
        date: 'Jueves 19',
        type: 'run',
        emoji: '🏃',
        title: 'Trote — 8–9 km',
        detail: 'Ritmo cómodo. En algún tramo podés subir a 5:30/km por 10–15 min para acostumbrarte al ritmo objetivo de la carrera.',
      },
      {
        id: 'day-11',
        date: 'Viernes 20',
        type: 'free',
        emoji: '🎉',
        title: 'Día libre',
        detail: 'Aprovechá. El sábado también es libre. Igual, recordá que el domingo viene la rodada más importante del plan.',
      },
      {
        id: 'day-12',
        date: 'Sábado 21',
        type: 'free',
        emoji: '🎉',
        title: 'Día libre',
        detail: 'Descansá. Hidratate bien — la rodada larga del domingo 22 es el entrenamiento más importante del plan.',
      },
      {
        id: 'day-13',
        date: 'Domingo 22',
        type: 'run',
        emoji: '🏃',
        title: 'Rodada larga — 16–17 km 🔑',
        detail: '⭐ ENTRENAMIENTO CLAVE. Ritmo suave 6:10–6:30/km. Obligatorio llevar agua. Si llegás a 16 km, ya sabés que los 21 están al alcance. No importa el tiempo, importa llegar.',
      },
    ],
  },
  {
    id: 3,
    title: 'Semana 3',
    subtitle: 'Tapering + Carrera',
    note: null,
    days: [
      {
        id: 'day-14',
        date: 'Lunes 23',
        type: 'rest',
        emoji: '😴',
        title: 'Descanso total',
        detail: 'Recuperación post-rodada larga. Importante de verdad: el descanso es parte del entrenamiento.',
      },
      {
        id: 'day-15',
        date: 'Martes 24',
        type: 'run',
        emoji: '🏃',
        title: 'Trote muy suave — 5 km',
        detail: 'Muy suave, 6:20–6:30/km. Solo para mantener el ritmo activo. Sin cansarte.',
      },
      {
        id: 'day-16',
        date: 'Miércoles 25',
        type: 'strength',
        emoji: '💪',
        title: 'Activación suave + estiramiento pre-carrera',
        detail: [
          {
            title: 'Importante — semana de tapering',
            items: [
              'No es el momento de esforzarse. El objetivo es activar sin cansar.',
              'Si algún ejercicio te duele o te sentís pesado, saltéalo. La carrera es el domingo.',
            ],
          },
          {
            title: 'Activación (15 min) — 2 rondas, lento y controlado',
            items: [
              'Sentadillas suaves ×12 — sin salto, bajás lento, subís lento',
              'Puente de glúteos ×15 — activás los glúteos que van a trabajar el domingo',
              'Clamshell ×15 c/lado — acostado de lado, rodilla superior hacia arriba como una almeja, sin mover la cadera',
              'Bird-dog ×10 c/lado — cuatro apoyos, extendés brazo y pierna opuestos, super controlado',
              'Plancha frontal ×30 seg — mantenés la tensión, nada más',
              'Elevación de talones parado ×15 — activás los gemelos, bajás lento',
            ],
          },
          {
            title: 'Estiramiento completo (15 min — el más largo del plan)',
            items: [
              'Gemelos contra la pared: 45 seg c/lado × 2 — hacé presión activa con el talón en el piso',
              'Isquiotibiales sentado: 45 seg × 2 — inclinación al frente, espalda larga, sin redondear',
              'Cuádriceps de pie: 40 seg c/lado — si perdés equilibrio, mano en la pared',
              'Psoas en estocada baja: 50 seg c/lado — rodilla en el piso, cadera hacia adelante, tronco recto',
              'Glúteos figura 4 acostado: 40 seg c/lado — jalás suave la pierna hacia el pecho',
              'TFL/cintilla: 35 seg c/lado — parado, cruzás una pierna delante, inclinás el tronco al lado contrario',
              'Espalda baja pose del niño: 2 min — brazos extendidos, frente en el piso, respirás profundo',
              'Rotación columna acostado: 30 seg c/lado — rodillas dobladas, las tirás al costado mientras el brazo opuesto va al otro lado',
            ],
          },
        ],
      },
      {
        id: 'day-17',
        date: 'Jueves 26',
        type: 'run',
        emoji: '🏃',
        title: 'Trote corto — 4–5 km',
        detail: 'Muy suave. Las piernas deben estar frescas para el domingo. No es el momento de esforzarse.',
      },
      {
        id: 'day-18',
        date: 'Viernes 27',
        type: 'free',
        emoji: '🎉',
        title: 'Día libre',
        detail: 'Podés salir tranquilo. Intentá no irte muy tarde — el domingo es el día grande.',
      },
      {
        id: 'day-19',
        date: 'Sábado 28',
        type: 'rest',
        emoji: '😴',
        title: 'Descanso total + preparación',
        detail: 'Preparás la ropa y el calzado. Comé bien durante el día (carbos, nada pesado a la noche). Dormí temprano. Hidratate.',
      },
      {
        id: 'day-20',
        date: 'Domingo 29',
        type: 'race',
        emoji: '🏁',
        title: '21 KM — ¡La promesa! 🎯',
        detail: 'Ritmo objetivo: 5:50–6:10/km → llegás en ~2:05–2:10 hs. Arrancá conservador los primeros 5 km. Hidratate cada 3–4 km. Caminá si lo necesitás — no es rendirse, es estrategia. Un kilómetro a la vez. ¡Podés hacerlo!',
      },
    ],
  },
]

export const tips = [
  {
    id: 'tip-food',
    icon: '🥗',
    title: 'Alimentación sin gastar de más',
    items: [
      'Arroz, fideos, papa y batata son tus mejores amigos. Carbos baratos. Aumentalos el día antes de cada rodada larga.',
      'Huevo: proteína barata y completa. Intentá comer 2–3 por día en los días de entrenamiento.',
      'Banana o naranja antes de correr. Barata y te da energía rápida disponible.',
      'Legumbres (lentejas, garbanzos): proteína + hierro. Ideales post-rodada larga.',
      'No necesitás gel ni suplemento para 21 km. Con comer bien antes alcanza perfectamente.',
      'La noche anterior a la carrera: plato de pastas o arroz. Nada nuevo, nada pesado.',
      'Mañana del 29: comé 2 horas antes de salir. Banana + tostadas o arroz con algo. Café si lo tomás normalmente.',
    ],
  },
  {
    id: 'tip-hydration',
    icon: '💧',
    title: 'Hidratación',
    items: [
      'Tomá agua a lo largo del día, no solo cuando tenés sed.',
      'Antes de correr: 1 vaso de agua 30 min antes. No sobrehidrates.',
      'En rodadas largas (+12 km): llevá una botellita o planificá fuentes / kioscos en el recorrido.',
      'Si el viernes o sábado tomás alcohol: el domingo hidratate el doble antes de salir a correr.',
      'El día de la carrera llevá agua sí o sí, aunque sea una botellita de 500 ml.',
    ],
  },
  {
    id: 'tip-stretch',
    icon: '🧘',
    title: 'Rutina de estiramiento (20–25 min)',
    items: [
      'Gemelos: contra la pared, pierna extendida atrás, 30 seg por pierna × 2.',
      'Isquiotibiales: sentado en el piso, piernas extendidas, inclinación al frente, 30 seg × 2.',
      'Cuádriceps: parado, tobillo al glúteo, 30 seg por lado × 2.',
      'Cadera flexora (psoas): estocada baja, rodilla en el piso, 40 seg por lado.',
      'Glúteos: acostado, rodilla al pecho, luego cruzada al lado contrario, 30 seg por lado.',
      'Espalda baja: "pose del niño" en el piso, 1 min. O rodillas al pecho acostado.',
      'Hacé esto después de correr, no antes (pre-carrera: calentá trotando 5 min suave).',
    ],
  },
  {
    id: 'tip-gear',
    icon: '👟',
    title: 'Equipamiento y logística',
    items: [
      'Usá las zapatillas con las que ya venís corriendo. No estrenes nada nuevo antes de la carrera.',
      'Medias sin costuras o con costura mínima. Las ampollas arruinan una carrera.',
      'Ropa: lo que uses normalmente. Si hace calor, evitá remeras de algodón (retienen el sudor y rozan).',
      'Vaselina o talco en los puntos de roce si sabés que tenés problemas (axilas, entrepierna, pezones).',
      'El día D: preparate todo la noche anterior. Ropa, zapatillas, agua, todo listo.',
    ],
  },
  {
    id: 'tip-warning',
    icon: '⚠️',
    title: 'Señales para parar o bajar el ritmo',
    items: [
      'Dolor de rodilla, cadera o tibias que no desaparece al calentar → pará y descansá ese día.',
      'Molestia en el tendón de Aquiles o en la planta del pie → no fuerces, es la lesión más común en corredores.',
      'Mareo o náuseas durante la carrera → caminá, tomá agua, sentate si hace falta.',
      'Falta de aire que no mejora al bajar el ritmo → pará y recuperate.',
      'Siempre es mejor llegar al 29 descansado que lesionado. Un día perdido no arruina el plan; una lesión sí.',
    ],
  },
  {
    id: 'tip-mental',
    icon: '🧠',
    title: 'Estrategia mental para el día de la carrera',
    items: [
      'Km 1–5: más lento de lo que querés ir. Guardá energía para la segunda mitad.',
      'Km 5–15: tu ritmo objetivo (~6:00–6:10/km). Tenés que poder hablar si quisieras.',
      'Km 15–21: lo que te quede en el tanque. Apretá si te sentís bien.',
      'Caminá 60 segundos si lo necesitás. No es rendirse, es estrategia para terminar.',
      'Mentalidad: "un kilómetro a la vez". No pienses en los 21, pensá en el próximo.',
      'Cuando el cuerpo diga que pares alrededor del km 14–16, es mentira. Ahí empieza la parte interesante.',
    ],
  },
]
